name = "bildr-meets"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "466788bf94b994a7922cbd15b834fe9b"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

[assets]
directory = "./public"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "bildr-meets-db"
database_id = "efd53a1f-c2c6-4bfb-b414-8cca83d4dab4"
